### PR TITLE
Read from an abbreviations file outside of titlecase() and only when invoked from command line

### LINKED ISSUE #58: It is impossible to prevent titlecase() from reading the ‘~/.titlecase.txt’ file
It makes sense to have that behavior as default for the `titlecase`
*command* (especially when it is invoked directly by the user from
the command line), but not for the `titlecase()` *function* that may be
called from some library code, which should not be accessing the file
system at all!

Besides, when writing a script using `titlecase()`, one often needs to
have a way to ensure consistent results across all users’ machines,
regardless of what each particular user has in their `~/.titlecase.txt`
file (and whether they have the file at all). Also, as for libraries,
for some scripts it may not even be appropriate (nor allowed) to
access the user’s file system.

I propose to change the behavior of the `titlecase()` function to, at
the very least, not attempt reading `~/.titlecase.txt` (or any other
files, for that matter) when its `wordlist_file` argument has the
value of `None`. In general, unless an effort is made by the caller,
the call to `titlecase()` should *not* incur any filesystem operations.

I have made the minimal required fix for that in #59.

### PR DESCRIPTION
**Pull request by iburago**
If the `titlecase()` function is called directly (say, from a library),
the caller can still use a custom list of abbreviations by passing
an appropriate function as `callback`.

Fixes #58.

### CODE REVIEW

**Comment by iburago** [comment]
If we choose this PR over #59, we might want to also add the
`create_wordlist_filter` function to `__all__` in order to export
it along with the `titlecase` function (in which case I would
rename the former to `create_wordlist_filter_from_file`).
Let me know whether you want that to be added to this PR.

**Comment by iburago** [comment]
As a side note, I’m also not a fan of having that `logger.debug()`
call in the `titlecase()`. When the `titlecase()` is called frequently,
it might have a small performance cost. However tiny it is, it is still
annoying for such a small library function like `titlecase()`.

I would remove it from there or, at least, protect it with `if __debug__:`.

**Comment by 1kastner** [comment]
I don't believe that this library targets high-performance use cases. Moreover, one old programmer's wisdom: Only optimize if you need to optimize! As long as there is no urge, it might be a waste of time and it might clutter the code. I could be persuaded by proper benchmarks though. In addition, have you checked the logging library whether they maybe already have something similar in place? I *guess* they did optimize their code.

**Comment by 1kastner** [comment]
To be honest, for my use case I only care about the command line interface so the internals do not bother me so much as long as nothing breaks, there are tests, and everything is nicely documented.

**Comment by iburago** [comment]
The code protected by `if __debug__:` is optimized out when the code
is loaded into the interpreter and, therefore, has no performance cost
during interpretation later on.

The logger’s `debug()` method in the `logging` module does check
whether the debug level of logging is enabled, and does not log the
given message otherwise. But one still pays the (however small)
performance cost of the function call and the log-level check.

It is unfortunate that no benchmarks were made when this logging
code was added. It is adding code that may clutter, not removing it.

I do not have time to do benchmarks at the moment, so, as I said
previously, I would be all right with keeping the logging code for
now, as long as we merge this PR (it contains no edits to the
logging code). It was just my side node.

**Comment by iburago** [comment]
As to the subject of this PR, your interest is not affected, then, since:

1. The command-line interface is not affected at all, and the command
has exactly the same default behavior of reading the `~/.titlecase.txt`
abbreviations file.

2. Those who are using the package as a library by just calling the
`titlecase()` function directly, still have the ability to filter by
the abbreviations from an abbreviations file by passing the
appropriate callback. The `create_wordlist_filter()` building
that callback is available to the user, so that a call

	titlecase(str, wordlist_filter=file_path)

simply changes to

	titlecase(str, callback=create_wordlist_filter(file_path))

3. The test for the wordlist file functionality in the `tests.py` file
was modified to use the new approach (just like shown above).
The tests are all passed.

**Comment by iburago** [comment]
Let me reiterate the advantages of this PR (which I mentioned in #58 

1. **Separation of concerns.** `titlecase()` is kept to its main function
of title-casing a given string, and does not suffer from having any
particular abbreviation-list mechanism being embedded into it.

2. **Simplification of the API without loss of functionality.** `titlecase()`
still has (the original) mechanism for supporting any exceptions in
capitalization through the interface of the `callback` function. That
is, `titlecase()` sees a single interface for all kinds of custom words,
regardless from their origin.

3. **Abbreviation file parsing is still available through a callback.**
The `create_wordlist_filter()` function is kept around for use (with
the primary instance being the command implementation in `cmd()`).
It is just that, when loading abbreviations from a file is desired, the
call to `create_wordlist_filter()` is to happen outside of `titlecase()`
(as opposed to inside in the current version).

**Comment by 1kastner** [comment]
That sounds great to me!

**Comment by ppannuto** [comment]
This makes a lot of sense to me. I was probably a little quick to move on pushing out the prior iteration of this, it had just sat for a while so I felt bad.

Strictly speaking, I think this will also require a 2.0 release as it changes the interface; not that I think a ton of folks have pulled the 1.0 version yet, but I would like to try to be a good citizen of the semver universe.

**Comment by iburago** [comment]
Changing the major version number due to the change of the API
makes total sense.

However, unless you have to, could you please postpone making
a new release? I have another couple of pull request in the works
for cleaning up the regular-expression constants, for making it
easier for the user to provide the list of custom small words, and,
possibly, for doing some minor refactoring.

**Comment by ppannuto** [comment]
No urgency to release here. Excited to see the new PRs!

**Pull request merged**
