### PR TITLE
[WIP] Add sphinx documentation to titlecase function

### PR DESCRIPTION
**Pull request by 1kastner**
What does `small_first_last` solve?

### CODE REVIEW

**Comment by ppannuto** [comment]
That came from #23, specifically it handles things like "and/or"

**Comment by 1kastner** [comment]
Do you like the sphinx documentation style in general?

**Comment by ppannuto** [comment]
I think so yeah, as I understand it's the de-facto standard for Python, so I think it makes sense to use.

**Comment by 1kastner** [comment]
Thank you @ppannuto for picking this up!

**Pull request merged**
